#!/usr/bin/env python

from apacheconfig import *
import argparse
import json
import os

options = {
    'lowercasenames': True
}

parser = argparse.ArgumentParser(description='List apache virtual hosts.')
parser.add_argument('--dump-config', action='store_true')

args = parser.parse_args()

available_path = "/etc/apache2/sites-available/"
enabled_path = "/etc/apache2/sites-enabled/"
websites = ["sysmon.ddns.net", "sysapi.ddns.net", "test.local"]


def main():
    """set default values"""
    is_enabled = False
    has_ssl = False

    data = dict()
    with make_loader(**options) as loader:
        for f in websites:
            """set enabled to true if the config exists in sites-enabled"""
            if os.path.isfile(enabled_path + f + ".conf"):
                is_enabled = True
            else:
                is_enabled = False

            """set ssl to true if an ssl config exists"""
            if os.path.isfile(available_path + f + "-le-ssl.conf"):
                has_ssl = True
            else:
                has_ssl = False

            config = loader.load(available_path + f + ".conf")
            """loop through each config and format data for response"""
            if len(config) > 0 and "virtualhost" in config:
                vhost = config["virtualhost"]["*:80"]

                data[vhost["servername"]] = {
                    "enabled": is_enabled,
                    "ssl": has_ssl
                }

                """attach the raw configuration if --dump-config is passed"""
                if args.dump_config is True:
                    data[vhost["servername"]]["config"] = vhost

    """format the json response"""
    print(json.dumps(data, indent=2))


if __name__ == "__main__":
    main()
